export const GET_PACKAGE_INITIATED = "GET_PACKAGE_INITIATED";
export const GET_PACKAGE_SUCCESS = "GET_PACKAGE_SUCCESS";
export const GET_PACKAGE_ERROR = "GET_PACKAGE_ERROR";

export const SAVE_PRODUCT_PACKAGE_INITIATED = "SAVE_PRODUCT_PACKAGE_INITIATED";
export const SAVE_PRODUCT_PACKAGE_SUCCESS = "SAVE_PRODUCT_PACKAGE_SUCCESS";
export const SAVE_PRODUCT_PACKAGE_ERROR = "SAVE_PRODUCT_PACKAGE_ERROR";

export const GET_PRODUCT_PACKAGE_INITIATED = "GET_PRODUCT_PACKAGE_INITIATED";
export const GET_PRODUCT_PACKAGE_SUCCESS = "GET_PRODUCT_PACKAGE_SUCCESS";
export const GET_PRODUCT_PACKAGE_ERROR = "GET_PRODUCT_PACKAGE_ERROR";

export const DELETE_PRODUCT_PACKAGE_INITIATED = "DELETE_PRODUCT_PACKAGE_INITIATED";
export const DELETE_PRODUCT_PACKAGE_SUCCESS = "DELETE_PRODUCT_PACKAGE_SUCCESS";
export const DELETE_PRODUCT_PACKAGE_ERROR = "DELETE_PRODUCT_PACKAGE_ERROR";

export const GET_PACKAGE_BY_ID_INITIATED = "GET_PACKAGE_BY_ID_INITIATED";
export const GET_PACKAGE_BY_ID_SUCCESS = "GET_PACKAGE_BY_ID_SUCCESS";
export const GET_PACKAGE_BY_ID_ERROR = "GET_PACKAGE_BY_ID_ERROR";