export const ADD_WITHDARAW_MONEY_INITIATED = "ADD_WITHDARAW_MONEY_INITIATED";
export const ADD_WITHDARAW_MONEY_SUCCESS = "ADD_WITHDARAW_MONEY_SUCCESS";
export const ADD_WITHDARAW_MONEY_ERROR = "ADD_WITHDARAW_MONEY_ERROR";

export const TARANSACTION_HISTORY_INITIATED = "TARANSACTION_HISTORY_INITIATED";
export const TARANSACTION_HISTORY_SUCCESS = "TARANSACTION_HISTORY_SUCCESS";
export const TARANSACTION_HISTORY_ERROR = "TARANSACTION_HISTORY_ERROR";

export const GET_CURRENTBALENCE_INITIATED = "GET_CURRENTBALENCE_INITIATED";
export const GET_CURRENTBALENCE_SUCCESS = "GET_CURRENTBALENCE_SUCCESS";
export const GET_CURRENTBALENCE_ERROR = "GET_CURRENTBALENCE_ERROR";