const PartnersConst = {
  partners: "Partner's",
  title: "Delete Partner",
  content: "Are you sure you want to remove Partner?",
  yes: "Yes",
  no: "No",
  colon: ":",
  companyname: "Company Name",
  email: "Email ID",
  mobile: "Mobile No",
  gst: "GST Type",
  gstno: "GstNumber",
  pan: "Pan",
  aadhar: "AadharNumber",
  bank: "Bank Name",
  branch: "Branch Name",
  address: "Address",
  account: "Account Number",
  ifsc: "Ifsc Code",
  pincode: "Pincode",
  state: "State",
  city: "City",
  contactname: "Contact Name",
  designation: "Designation",
};
export { PartnersConst };
