export const GET_USER_RIGHTS_INITIATED = "GET_USER_RIGHTS_INITIATED";
export const GET_USER_RIGHTS_SUCCESS = "GET_USER_RIGHTS_SUCCESS";
export const GET_USER_RIGHTS_ERROR = " GET_USER_RIGHTS_ERROR";

export const SAVE_USER_INITIATED = "SAVE_USER_INITIATED";
export const SAVE_USER_SUCCESS = "SAVE_USER_SUCCESS";
export const SAVE_USER_ERROR = "SAVE_USER_ERROR";

export const GET_USERS_INITIATED = "GET_USERS_INITIATED";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_ERROR = "GET_USERS_ERROR";

export const DELETE_USER_INITIATED = "DELETE_USER_INITIATED";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_ERROR = "DELETE_USER_ERROR";

export const GET_USER_BY_ID_INITIATED = "GET_USER_BY_ID_INITIATED";
export const GET_USER_BY_ID_SUCCESS = "GET_USER_BY_ID_SUCCESS";
export const GET_USER_BY_ID_ERROR = "GET_USER_BY_ID_ERROR";
