const TableConst = {
  view: "View",
  edit: "Edit",
  wallet: "Wallet",
  prospect: "Prospect",
  sales: "Sales",
  delete: "Delete",
  status: "Status",
  curPwd: "Current Password",
  entCurPwd: "Enter Current Password",
  newPwd: "New Password",
  entNewPwd: "Enter New Password",
  cunfNewPwd: "Confirm New Password",
  colon: ":",
  star: "*",
  sr: "#",
  srNo: "Sr No.",
  notif: "Notifications",
  no: "No",
  va: "View All",
  email: "Email",
  search: "Search...",
  mobile: "Mobile Number",
  address: "Address",
  rem: "Remarks",
  emid: "Email ID",
  cusName: "Customer Name",
  cusSelect: "Customer Selection",
  lt: "Lead type",
  pro: "Product",
  demo: "Demo",
  sale: "Sale",
  ProName: "Prospect Name",
  contNum: "Contact Number",
  leadName: "Lead Name",
  action: "Action",
  number: "Number",
  name: "Name",
  msg: "Message",
  phonNo: "Phone No.",
  entYoNa: "Enter Your Name",
  entYoEmaAdd: "Enter Your Email Address",
  entYoPhoNo: "Enter Your Phone No.",
  saleslist: "Sales List",
  addNeSal: "Add New Sales",
  liceId: "Licence Id",
  subType: "Subscription Type",
  expIn: "Expires in",
  lead: "Lead",
  gstType: "GST Type",
  timePer: "Time Period",
  gstno: "GST No.",
  firstName: "First Name",
  middleName: "Middle Name",
  lastName: "Last Name",
};
export { TableConst };
