export const SAVE_PROSPECT_INITIATED = "SAVE_PROSPECT_INITIATED";
export const SAVE_PROSPECT_SUCCESS = "SAVE_PROSPECT_SUCCESS";
export const SAVE_PROSPECT_ERROR = "SAVE_PROSPECT_ERROR";

export const GET_PROSPECT_INITIATED = "GET_PROSPECT_INITIATED";
export const GET_PROSPECT_SUCCESS = "GET_PROSPECT_SUCCESS";
export const GET_PROSPECT_ERROR = "GET_PROSPECT_ERROR";

export const DELETE_PROSPECT_INITIATED = "DELETE_PROSPECT_INITIATED";
export const DELETE_PROSPECT_SUCCESS = "DELETE_PROSPECT_SUCCESS";
export const DELETE_PROSPECT_ERROR = "DELETE_PROSPECT_ERROR";

export const GET_CUSTOMER_INITIATED = "GET_CUSTOMER_INITIATED";
export const GET_CUSTOMER_SUCCESS = "GET_CUSTOMER_SUCCESS";
export const GET_CUSTOMER_ERROR = "GET_CUSTOMER_ERROR";

export const GET_LEAD_TYPE_INITIATED = "GET_LEAD_TYPE_INITIATED";
export const GET_LEAD_TYPE_SUCCESS = "GET_LEAD_TYPE_SUCCESS";
export const GET_LEAD_TYPE_ERROR = "GET_LEAD_TYPE_ERROR";

export const GET_PRODUCT_INITIATED = "GET_PRODUCT_INITIATED";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR";

export const SAVE_LEADS_INITIATED = "SAVE_LEADS_INITIATED";
export const SAVE_LEADS_SUCCESS = "SAVE_LEADS_SUCCESS";
export const SAVE_LEADS_ERROR = "SAVE_LEADS_ERROR";

export const GET_LEADS_INITIATED = "GET_LEADS_INITIATED";
export const GET_LEADS_SUCCESS = "GET_LEADS_SUCCESS";
export const GET_LEADS_ERROR = "GET_LEADS_ERROR";

export const DELETE_LEAD_INITIATED = "DELETE_LEAD_INITIATED";
export const DELETE_LEAD_SUCCESS = "DELETE_LEAD_SUCCESS";
export const DELETE_LEAD_ERROR = " DELETE_LEAD_ERROR";

export const GET_PRODUCT_BY_CUSTOMER_INITIATED =
  "GET_PRODUCT_BY_CUSTOMER_INITIATED";
export const GET_PRODUCT_BY_CUSTOMER_SUCCESS =
  "GET_PRODUCT_BY_CUSTOMER_SUCCESS";
export const GET_PRODUCT_BY_CUSTOMER_ERROR = "GET_PRODUCT_BY_CUSTOMER_ERROR";

export const SAVE_DEMO_INITIATED = "SAVE_DEMO_INITIATED";
export const SAVE_DEMO_SUCCESS = "SAVE_DEMO_SUCCESS";
export const SAVE_DEMO_ERROR = "SAVE_DEMO_ERROR";

export const GET_DEMO_INITIATED = "GET_DEMO_INITIATED";
export const GET_DEMO_SUCCESS = "GET_DEMO_SUCCESS";
export const GET_DEMO_ERROR = "GET_DEMO_ERROR";

export const DELETE_DEMO_INITIATED = "DELETE_DEMO_INITIATED";
export const DELETE_DEMO_SUCCESS = "DELETE_DEMO_SUCCESS";
export const DELETE_DEMO_ERROR = "DELETE_DEMO_ERROR";

export const GET_PARTNER_PRODUCT_INITIATED = "GET_PARTNER_PRODUCT_INITIATED";
export const GET_PARTNER_PRODUCT_SUCCESS = "GET_PARTNER_PRODUCT_SUCCESS";
export const GET_PARTNER_PRODUCT_ERROR = "GET_PARTNER_PRODUCT_ERROR";

export const GET_PRODUCT_SUBSCRIPTION_INITIATED =
  "GET_PRODUCT_SUBSCRIPTION_INITIATED";
export const GET_PRODUCT_SUBSCRIPTION_SUCCESS =
  "GET_PRODUCT_SUBSCRIPTION_SUCCESS";
export const GET_PRODUCT_SUBSCRIPTION_ERROR = "GET_PRODUCT_SUBSCRIPTION_ERROR";

export const GET_LEAD_CUSTOMER_INITIATED = "GET_LEAD_CUSTOMER_INITIATED";
export const GET_LEAD_CUSTOMER_SUCCESS = "GET_LEAD_CUSTOMER_SUCCESS";
export const GET_LEAD_CUSTOMER_ERROR = "GET_LEAD_CUSTOMER_ERROR";

export const SAVE_SALES_INITIATED = "SAVE_SALES_INITIATED";
export const SAVE_SALES_SUCCESS = "SAVE_SALES_SUCCESS";
export const SAVE_SALES_ERROR = "SAVE_SALES_ERROR";

export const GET_SALES_INITIATED = "GET_SALES_INITIATED";
export const GET_SALES_SUCCESS = "GET_SALES_SUCCESS";
export const GET_SALES_ERROR = "GET_SALES_ERROR";
