export const SAVE_PARTNER_INITIATED = "SAVE_PARTNER_INITIATED";
export const SAVE_PARTNER_SUCCESS = "SAVE_PARTNER_SUCCESS";
export const SAVE_PARTNER_ERROR = "SAVE_PARTNER_ERROR";

export const GET_PARTNERS_INITIATED = "GET_PARTNERS_INITIATED";
export const GET_PARTNERS_SUCCESS = "GET_PARTNERS_SUCCESS";
export const GET_PARTNERS_ERROR = "GET_PARTNERS_ERROR";

export const DELETE_PARTNER_INITIATED = "DELETE_PARTNER_INITIATED";
export const DELETE_PARTNER_SUCCESS = "DELETE_PARTNER_SUCCESS";
export const DELETE_PARTNER_ERROR = "DELETE_PARTNER_ERROR";

export const GET_PARTNER_BY_ID_INITIATED = "GET_PARTNER_BY_ID_INITIATED";
export const GET_PARTNER_BY_ID_SUCCESS = "GET_PARTNER_BY_ID_SUCCESS";
export const GET_PARTNER_BY_ID_ERROR = "GET_PARTNER_BY_ID_ERROR";
