export const LOGIN_PARTNER_INITIATED = "LOGIN_PARTNER_INITIATED";
export const LOGIN_PARTNER_SUCCESS = "LOGIN_PARTNER_SUCCESS";
export const LOGIN_PARTNER_ERROR = "LOGIN_PARTNER_ERROR";

export const FORGET_PASSWORD_PARTNER_INITIATED =
  "FORGET_PASSWORD_PARTNER_INITIATED";
export const FORGET_PASSWORD_PARTNER_SUCCESS =
  "FORGET_PASSWORD_PARTNER_SUCCESS";
export const FORGET_PASSWORD_PARTNER_ERROR = "FORGET_PASSWORD_PARTNER_ERROR";

export const SAVE_CONTACTUS_INITIATED = "SAVE_CONTACTUS_INITIATED";
export const SAVE_CONTACTUS_SUCCESS = "SAVE_CONTACTUS_SUCCESS";
export const SAVE_CONTACTUS_ERROR = "SAVE_CONTACTUS_ERROR";

export const SAVE_SUPPORT_INITIATED = "SAVE_SUPPORT_INITIATED";
export const SAVE_SUPPORT_SUCCESS = "SAVE_SUPPORT_SUCCESS";
export const SAVE_SUPPORT_ERROR = "SAVE_SUPPORT_ERROR";
