export const SAVE_CONTACTUS_INITIATED = "SAVE_CONTACTUS_INITIATED";
export const SAVE_CONTACTUS_SUCCESS = "SAVE_CONTACTUS_SUCCESS";
export const SAVE_CONTACTUS_ERROR = "SAVE_CONTACTUS_ERROR";

export const SAVE_SUPPORT_INITIATED = "SAVE_SUPPORT_INITIATED";
export const SAVE_SUPPORT_SUCCESS = "SAVE_SUPPORT_SUCCESS";
export const SAVE_SUPPORT_ERROR = "SAVE_SUPPORT_ERROR";
